// desktop/frontend/src/views/Devices.vue
<template>
    <div>
        <n-page-header title="设备控制" style="margin-bottom: 16px">
            <template #extra>
                <n-space align="center" :size="8">
                    <n-tag :type="wsTagType" size="small" round>
                        ● {{ wsStatusText }}
                    </n-tag>
                    <n-button size="small" :loading="loadingDevices" :disabled="!selectedNode" @click="refreshDevices">↻ 刷新</n-button>
                </n-space>
            </template>
        </n-page-header>
        <n-select
            v-model:value="selectedNode"
            :options="nodeOptions"
            placeholder="选择节点"
            style="margin-bottom: 16px"
            :loading="loadingNodes"
        />
        <n-empty v-if="!selectedNode" description="请先选择一个节点" style="padding: 32px 0" />
        <n-spin v-else :show="loadingDevices && !devices.length">
            <n-empty v-if="!devices.length && !loadingDevices" description="该节点暂无设备" style="padding: 32px 0" />
            <n-space vertical :size="8">
                <n-card v-for="d in devices" :key="d.deviceId" size="small">
                    <div style="display: flex; align-items: center; justify-content: space-between">
                        <div style="display: flex; flex-direction: column; gap: 4px; min-width: 0">
                            <span style="font-size: 15px; font-weight: 600">{{ d.friendlyName }}</span>
                            <n-space :size="6">
                                <n-tag size="tiny" :bordered="false">{{ d.deviceId.slice(0, 16) }}</n-tag>
                                <n-tag v-if="d.model" size="tiny" :bordered="false">{{ d.model }}</n-tag>
                                <n-tag v-if="d.type" size="tiny" :bordered="false">{{ d.type }}</n-tag>
                            </n-space>
                        </div>
                        <n-switch
                            v-if="d.supportsOnOff !== false"
                            :value="d.currentState === 'ON'"
                            :loading="toggling.has(d.deviceId)"
                            :disabled="toggling.has(d.deviceId)"
                            @update:value="onToggle(d)"
                        />
                    </div>
                </n-card>
            </n-space>
        </n-spin>
    </div>
</template>

<script setup lang="ts">
import {
  NPageHeader, NSpace, NSelect, NButton, NEmpty, NCard, NTag, NSwitch, NSpin, useMessage,
} from 'naive-ui';
import {
  computed, onMounted, onUnmounted, reactive, ref, watch,
} from 'vue';
import {
  fetchNodes, fetchNodeDevices, controlDevice, type EdgeNode, type Device,
} from '../api';
import { subscribeDeviceStates, wsState } from '../ws';

const message = useMessage();
const nodes = ref<EdgeNode[]>([]);
const selectedNode = ref<string | null>(null);
const devices = ref<Device[]>([]);
const loadingNodes = ref(false);
const loadingDevices = ref(false);
const toggling = reactive(new Set<string>());
let unsubscribe: (() => void) | undefined;

const nodeOptions = computed(() => nodes.value.map((n) => ({
  label: `${n.nodeId} (${n.host}:${n.port})`,
  value: n.nodeId,
})));

const wsTagType = computed(() => (wsState.status === 'connected' ? 'success'
  : wsState.status === 'connecting' ? 'warning' : 'error'));
const wsStatusText = computed(() => (wsState.status === 'connected' ? '实时'
  : wsState.status === 'connecting' ? '连接中' : '未连接'));

async function refreshNodes() {
  loadingNodes.value = true;
  try {
    const res = await fetchNodes();
    nodes.value = res.nodes.filter((n) => n.status === 'online');
    if (!selectedNode.value && nodes.value.length) {
      selectedNode.value = nodes.value[0].nodeId;
    }
  } catch (e: any) {
    message.error(`获取节点失败：${e.message || e}`);
  } finally {
    loadingNodes.value = false;
  }
}

async function refreshDevices() {
  if (!selectedNode.value) return;
  loadingDevices.value = true;
  try {
    const res = await fetchNodeDevices(selectedNode.value);
    devices.value = res.devices;
  } catch (e: any) {
    message.error(`获取设备失败：${e.message || e}`);
  } finally {
    loadingDevices.value = false;
  }
}

async function onToggle(device: Device) {
  if (!selectedNode.value || toggling.has(device.deviceId)) return;
  toggling.add(device.deviceId);
  const newState = device.currentState === 'ON' ? 'OFF' : 'ON';
  try {
    await controlDevice(selectedNode.value, device.deviceId, newState);
    device.currentState = newState; // 乐观更新，WS 推送会再确认
  } catch (e: any) {
    message.error(`控制失败：${e.message || e}`);
  } finally {
    toggling.delete(device.deviceId);
  }
}

function onDeviceState(topic: string, payload: unknown) {
  const match = topic.match(/^node\/([^/]+)\/devices\/([^/]+)\/state$/);
  if (!match || match[1] !== selectedNode.value) return;
  const device = devices.value.find((d) => d.deviceId === match[2]);
  if (!device) return;
  let state: any = payload;
  if (typeof state === 'string') {
    try { state = JSON.parse(state); } catch { state = {}; }
  }
  const newState = state?.state === 'ON' ? 'ON' : state?.state === 'OFF' ? 'OFF' : undefined;
  if (newState) device.currentState = newState;
}

watch(selectedNode, () => {
  devices.value = [];
  refreshDevices();
});

onMounted(() => {
  refreshNodes();
  unsubscribe = subscribeDeviceStates((msg) => onDeviceState(msg.topic, msg.payload));
});
onUnmounted(() => unsubscribe?.());
</script>

// ui/app/pages/Devices.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { getServerUrl, loadCredentials, getSavedPassword, fetchNodes, fetchNodeDevices, controlDevice, EdgeNode, Device } from '../api';

const styles: Record<string, React.CSSProperties> = {
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    marginBottom: 16,
  },
  title: { fontSize: 18, fontWeight: 600, margin: 0 },
  select: {
    width: '100%',
    padding: '12px 14px',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 8,
    background: '#1a1a2e',
    color: '#e0e0e0',
    fontSize: 15,
    outline: 'none',
    marginBottom: 20,
    boxSizing: 'border-box' as const,
  },
  deviceList: { display: 'flex', flexDirection: 'column', gap: 8 },
  deviceCard: {
    background: '#16213e',
    borderRadius: 12,
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  deviceLeft: { display: 'flex', flexDirection: 'column', gap: 2, flex: 1, minWidth: 0 },
  deviceName: { fontSize: 15, fontWeight: 600 },
  deviceMeta: { fontSize: 12, color: '#8899aa', display: 'flex', gap: 8, marginTop: 2 },
  metaTag: { background: 'rgba(255,255,255,0.06)', padding: '1px 8px', borderRadius: 4 },
  placeholder: { textAlign: 'center' as const, color: '#8899aa', padding: '32px 0', fontSize: 14 },
  refreshBtn: {
    background: 'none',
    border: 'none',
    color: '#8899aa',
    cursor: 'pointer',
    padding: 6,
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
  },
};

/* Toggle switch */
function Toggle({ checked, disabled, onChange }: { checked: boolean; disabled: boolean; onChange: () => void }) {
  const trackStyle: React.CSSProperties = {
    width: 48,
    height: 28,
    borderRadius: 28,
    background: checked ? '#00d2ff' : '#444',
    position: 'relative',
    cursor: disabled ? 'not-allowed' : 'pointer',
    transition: 'background 0.25s',
    opacity: disabled ? 0.4 : 1,
    flexShrink: 0,
    marginLeft: 12,
  };
  const thumbStyle: React.CSSProperties = {
    width: 22,
    height: 22,
    borderRadius: '50%',
    background: '#fff',
    position: 'absolute',
    top: 3,
    left: checked ? 23 : 3,
    transition: 'left 0.25s',
  };
  return (
    <div style={trackStyle} onClick={disabled ? undefined : onChange}>
      <div style={thumbStyle} />
    </div>
  );
}

export default function Devices() {
  const navigate = useNavigate();
  const [nodes, setNodes] = useState<EdgeNode[]>([]);
  const [selectedNode, setSelectedNode] = useState<string>('');
  const [devices, setDevices] = useState<Device[]>([]);
  const [loading, setLoading] = useState(false);
  const [toggling, setToggling] = useState<Set<string>>(new Set());
  const [wsStatus, setWsStatus] = useState<'connecting' | 'connected' | 'disconnected'>('disconnected');
  const serverUrl = getServerUrl();

  useEffect(() => {
    if (!serverUrl) navigate('/');
  }, [serverUrl, navigate]);

  // Load node list
  useEffect(() => {
    const load = async () => {
      try {
        const data = await fetchNodes();
        const onlineNodes = (data.nodes || []).filter((n) => n.status === 'online');
        setNodes(onlineNodes);
        if (onlineNodes.length > 0 && !selectedNode) {
          setSelectedNode(onlineNodes[0].nodeId);
        }
      } catch {
        setNodes([]);
      }
    };
    load();
    const interval = setInterval(load, 5000);
    return () => clearInterval(interval);
  }, [selectedNode]);

  // Load devices for selected node (initial load via HTTP)
  const loadDevices = useCallback(async () => {
    if (!selectedNode) return;
    setLoading(true);
    try {
      const data = await fetchNodeDevices(selectedNode);
      setDevices(data.devices || []);
    } catch {
      setDevices([]);
    } finally {
      setLoading(false);
    }
  }, [selectedNode]);

    // WebSocket for real-time device state updates (via Vite proxy)
  useEffect(() => {
    if (!selectedNode || !serverUrl) return;
    loadDevices();
    loadCredentials();

    const wsUrl = serverUrl.replace(/^https?/, (m) => (m === 'https' ? 'wss' : 'ws')) + '/api/edge/ws?token=' + encodeURIComponent(getSavedPassword());

    let ws: WebSocket | null = null;
    let reconnectTimer: ReturnType<typeof setTimeout>;

    function connect() {
      ws = new WebSocket(wsUrl);
      setWsStatus('connecting');

      ws.onopen = () => { setWsStatus('connected'); };
      ws.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data);
          if (msg.type !== 'device_state') return;
          const parts = msg.topic?.split('/') || [];
          if (parts[1] !== selectedNode || !parts[3]) return;
          let payload = msg.payload;
          if (typeof payload === 'string') { try { payload = JSON.parse(payload); } catch {} }
          const newState = payload?.state === 'ON' ? 'ON' : payload?.state === 'OFF' ? 'OFF' : undefined;
          if (newState) {
            setDevices((prev) => prev.map((d) =>
              d.deviceId === parts[3] ? { ...d, currentState: newState } : d
            ));
          }
        } catch {}
      };
      ws.onclose = () => {
        setWsStatus('disconnected');
        reconnectTimer = setTimeout(connect, 3000);
      };
      ws.onerror = () => ws?.close();
    }

    connect();
    return () => { clearTimeout(reconnectTimer); ws?.close(); };
  }, [selectedNode, serverUrl, loadDevices]);

  const handleToggle = async (device: Device) => {
    if (!selectedNode || !device.deviceId || toggling.has(device.deviceId)) return;

    setToggling((prev) => new Set(prev).add(device.deviceId));
    const newState = device.currentState === 'ON' ? 'OFF' : 'ON';
    try {
      await controlDevice(selectedNode, device.deviceId, newState);
      device.currentState = newState;
      setDevices([...devices]);
    } catch (err: any) {
      console.error('控制失败', err);
    } finally {
      setToggling((prev) => {
        const next = new Set(prev);
        next.delete(device.deviceId);
        return next;
      });
    }
  };

  return (
    <div>
      <div style={styles.headerRow}>
        <h2 style={styles.title}>设备控制</h2>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 11, color: wsStatus === 'connected' ? '#2ed573' : wsStatus === 'connecting' ? '#ffa502' : '#ff4757' }}>
            ● {wsStatus === 'connected' ? '实时' : wsStatus === 'connecting' ? '连接中' : '未连接'}
          </span>
          <button style={styles.refreshBtn} onClick={loadDevices}>↻ 刷新</button>
        </div>
      </div>

      <select
        style={styles.select}
        value={selectedNode}
        onChange={(e) => setSelectedNode(e.target.value)}
      >
        {nodes.length === 0 && <option value="">无在线节点</option>}
        {nodes.map((n) => (
          <option key={n.nodeId} value={n.nodeId}>
            {n.nodeId} ({n.host}:{n.port})
          </option>
        ))}
      </select>

      <div style={styles.deviceList}>
        {!selectedNode ? (
          <div style={styles.placeholder}>请选择一个节点</div>
        ) : loading ? (
          <div style={styles.placeholder}>加载中…</div>
        ) : devices.length === 0 ? (
          <div style={styles.placeholder}>该节点暂无设备</div>
        ) : (
          devices.map((d) => {
            const isOn = d.currentState === 'ON';
            return (
              <div key={d.deviceId} style={styles.deviceCard}>
                <div style={styles.deviceLeft}>
                  <span style={styles.deviceName}>{d.friendlyName}</span>
                  <span style={styles.deviceMeta}>
                    <span style={styles.metaTag}>{d.deviceId.slice(0, 16)}</span>
                    {d.model && <span style={styles.metaTag}>{d.model}</span>}
                    {d.type && <span style={styles.metaTag}>{d.type}</span>}
                  </span>
                </div>
                {d.supportsOnOff !== false && (
                  <Toggle
                    checked={isOn}
                    disabled={toggling.has(d.deviceId)}
                    onChange={() => handleToggle(d)}
                  />
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
